In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from ucimlrepo import fetch_ucirepo

iris = fetch_ucirepo(id=53)

X = iris.data.features
y = iris.data.targets

In [8]:
X.to_csv("predictor_bronze.csv", index=False)
y.to_csv("target_bronze.csv", index=False)

In [24]:
predictor_raw = pd.read_csv(
    "/Users/skier/MSDS/Spring2/Spring2-MSDS-MLOps/labs/lab3/data/predictor_bronze.csv"
)
target_raw = pd.read_csv(
    "/Users/skier/MSDS/Spring2/Spring2-MSDS-MLOps/labs/lab3/data/target_bronze.csv"
)

predictor_raw_encoded = predictor_raw.copy()

# Track column transformations
column_mapping = {}
label_encoders = {}

# Find all object and category columns
string_columns = predictor_raw.select_dtypes(
    include=["object", "category"]
).columns

for col in string_columns:
    # For columns with many unique values, use label encoding
    le = LabelEncoder()
    predictor_raw_encoded[col + "_encoded"] = le.fit_transform(
        predictor_raw[col]
    )

    # Drop the original column
    predictor_raw_encoded = predictor_raw_encoded.drop(col, axis=1)

    # Store mapping information
    column_mapping[col] = [col + "_encoded"]
    label_encoders[col] = le

X_silver = predictor_raw_encoded.astype(float)
y_silver = target_raw

In [27]:
Data_Silver = pd.concat([X_silver, y_silver], axis=1)
Data_Silver.to_csv("data/Iris_Silver.csv")
Data_Silver

     sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]